services:
  mongodb1:
    container_name: mongodb1
    image: dh-mirror.gitverse.ru/mongo:latest
    volumes:
      - mongodb1_data_container:/data/db

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongodb1
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://router01:27017/?directConnection=false"
      MONGODB_DATABASE_NAME: "somedb"
    networks:
      - mongo-sharding_default


volumes:
  mongodb1_data_container:

networks:
  mongo-sharding_default:
    external: true
